proj5.x: proj5.o proj5.cpp passserver.o passserver.cpp
	g++ -std=c++11 -Wall -pedantic -lcrypt -c -o proj5.o proj5.cpp
	g++ -std=c++11 -Wall -pedantic -lcrypt -c -o passserver.o passserver.cpp
	g++ -std=c++11 -Wall -pedantic -lcrypt -o proj5.x proj5.o passserver.o

cleam:
	rm proj5.x
